language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm run validate
deploy:
  - provider: npm
    email: 128techadmin@128technology.com
    skip_cleanup: true
    api_key:
      secure: qnLszql4MdHKExj0AiN3s9v7mxlMi2t28sNibcFTFGAx/RA5NUvsMZRw5Wk0Z3/JmiGVpkanzVl5d3hLcwUZidMtW3TxNi+edxleNI1uxQFPst/pXfJx+onUv6j0bNV9FfXfgw27qok/T+oNvoCdHSWMcsS64K9MSYiT+QAXEsUtO2qE1sKG76xXi9lE1VAiroO21yd3+p5eYs5ceM15Rq8DfL9/NyOM1J3AHQLYqBC0kT87U/baCf2l9CnyE1Huz+JHpgw886IJDHORbWQQODEafSHkwZbxeIeZ2tVo1LDckaGTDQAmWPphxvgqWpQpiZRahTdCWnECqQ6dVljLFWb29nkrXT3hcg45HYU9PyJP7kIIzWSCWUGX89pqURpJi1RZxODh/n7P44pV6H0TGivHjVL3B3ea4JzLZehcbTCEeYU+FvHMFZP0ZLOb5gFT3nttsfXI7/rTT8+04jzl8eACgfxk1yIv1t3g3bY1zubuHXoTtLjdohIDpEU3SLbknq+FG2UlOUu3i1KsZ3ZDsjUwiEHbfs9m/lMYF5vx3BhWnqlSAH6h/1ZypskmyMfq3MTA5e8z0LbTkAVJmX2cvBoYDp/aYsQSRAmxsBxmk9lcF4PQaFE0uEd1y9McLXtJIerhuV60L1XAY39fdGEY9YBKZlEdM4xwAr5P/33bOcs=
    on:
      repo: 128technology/netconfetti
      branch: master